name: cowsay_issue

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker/whalesay
    steps:
      - uses: actions/checkout@v2
      - name: test msg
        run: echo this is a test message on issues
      - name: cowsay test
        run: cowsay "Moo Moo"
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["cowsay"], "labels": ["TEST"]}, {"keywords": ["help", "guidance"], "labels": ["help-wanted"], "assignees": ["ilikeangrybanana"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
