name: mainworkflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: test msg
        run: echo this is a test message
      - name: run test
        run: npm run test
      - name: run failing test
        run: npm run test:fail