name: qwe_on_master

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: test msg
        run: echo this is a test message for qwe on master
      - name: run test
        run: npm run test
      - name: run failing test
        run: npm run test:fail